### ISSUE TITLE
[Bug] Crash on world join, value must be positive

### ISSUE THREAD

**Issue by ghost** [fabbe50/FogOverridesIssues#1] opened 2022-07-08 22:21 UTC
**Describe the bug**
Game crashes with an unknown value being "not postitive"

**To Reproduce**
Load into a world.

**Expected behavior**
Not crash and be free from ugly fog.

**Error**
```
java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:321) ~[?:?] {re:mixin}
	at com.fabbe50.fogoverrides.FogOverrides.particles(FogOverrides.java:126) ~[fogoverrides-1.18.2-1.1.2.jar%23147!/:1.18.2-1.1.2] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_1499_FogOverrides_particles_WorldTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%2343!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%2343!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%2343!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPreWorldTick(ForgeEventFactory.java:881) ~[forge-1.18.2-40.1.54-universal.jar%23281!/:?] {re:mixin,re:classloading}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:899) ~[client-1.18.2-20220404.173914-srg.jar%23276!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[client-1.18.2-20220404.173914-srg.jar%23276!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%23276!/:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%23276!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%23276!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {re:mixin}

java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:321) ~[?:?] {re:mixin}
	at com.fabbe50.fogoverrides.FogOverrides.particles(FogOverrides.java:126) ~[fogoverrides-1.18.2-1.1.2.jar%23147!/:1.18.2-1.1.2] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_1499_FogOverrides_particles_WorldTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%2343!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%2343!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%2343!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPreWorldTick(ForgeEventFactory.java:881) ~[forge-1.18.2-40.1.54-universal.jar%23281!/:?] {re:mixin,re:classloading}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:899) ~[client-1.18.2-20220404.173914-srg.jar%23276!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[client-1.18.2-20220404.173914-srg.jar%23276!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%23276!/:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%23276!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%23276!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {re:mixin}

```

Full log: https://mclo.gs/jmvgSmA

**Versions (please complete the following information):**
 - Minecraft Version: 1.18.2
 - Forge Version: 40.1.54
 - Mod Version: fogoverrides-1.18.2-1.1.2

**Additional context**

Not sure what config value is causing the crash. None of the values are set to negative except for the fire overlay offset which wasn't changed from default, if I am remembering right.

**Config Files:**

<details><summary>general.toml</summary>

```toml
[general]
	#Overrides are dependent on potion effects
	"Potion Active" = true
	#Creative Mode Always Removes Fog
	"Creative Overrides" = false
	#Disable the fire overlay when you're burning
	"Disable Fire Overlay" = false
	#Offset the fire overlay, negative values means down and positive is up.
	#Range: -1.0 ~ 1.0
	"Fire Overlay Offset" = -0.25
	#Disable the water overlay when you're in water
	"Disable Water Overlay" = false
```

</details>

<details><summary>lava.toml</summary>

```toml
[lava]
	#Disable Lava Fog?
	"Disable Lava Fog" = false
	#Lava Fog Starting Distance
	#Range: 0.1 ~ 100.0
	"Lava Fog Starting Distance" = 35.0
	#Lava Fog End Distance
	#Range: 0.1 ~ 100.0
	"Lava Fog End Distance" = 40.0
```

</details>

<details><summary>nether.toml</summary>

```toml
[nether]
	#Disable Nether Fog?
	"Disable Nether Fog" = true
	#Nether Fog Starting Distance
	#Range: 0.1 ~ 100.0
	"Nether Fog Starting Distance" = 1.0
	#Nether Fog End Distance
	#Range: 0.1 ~ 100.0
	"Nether Fog End Distance" = 1.7
```

</details>

<details><summary>overworld.toml</summary>

```toml
[overworld]
	#Disable Overworld Fog?
	"Disable Overworld Fog" = true
	#Overworld Fog Starting Distance
	#Range: 0.1 ~ 100.0
	"Overworld Fog Starting Distance" = 70.0
	#Overworld Fog End Distance
	#Range: 0.1 ~ 100.0
	"Overworld Fog End Distance" = 80.0
	#Readds the void fog that was removed in 1.8
	"Enable Void Fog" = true
	#This is so you can adjust the starting distance of the fog
	#Range: 0.001 ~ 10.0
	"Void Fog Starting Distance" = 9.0
	#This is so you can adjust the ending distance of the fog
	#Range: 0.001 ~ 10.0
	"Void Fog End Distance" = 10.0
	#At what Y-level should the fog active on
	#Range: -64 ~ 319
	"Y-Level Activation" = 0.0
	#Readds the void particles that was removed in 1.8
	"Enable Void Particles" = true
	#If the player is in a skylight level of 8, the fog disappears
	"Void scared of sky" = true
```

</details>

<details><summary>water.toml</summary>

```toml
[water]
	#Disable Water Fog?
	"Disable Water Fog" = false
	#Water Fog Starting Distance
	#Range: 0.1 ~ 50.0
	"Water Fog Starting Distance" = 40.0
	#Water Fog End Distance
	#Range: 0.1 ~ 50.0
	"Water Fog End Distance" = 50.0
```

</details>

**Comment by fabbe50** [comment] 2022-07-12 16:52
Caused by an issue with the particle placing function for the void particles. This is fixed in 1.1.3. Thank you

**Closed as completed by fabbe50** 2022-07-12 16:52 UTC
Labels: bug
